/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchengine;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak Mane
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    RecordEntry std = new RecordEntry();
    public MainForm() {
        initComponents();
        std.fillJTable(jTable, "");
        jTable.setRowHeight(45);
        jTable.setShowGrid(true);
        jTable.setGridColor(Color.blue);
        jTable.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelWel = new javax.swing.JLabel();
        BnameTextField = new javax.swing.JTextField();
        AnameTextField = new javax.swing.JTextField();
        PrcTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        jLabelWel.setFont(new java.awt.Font("Yu Gothic", 2, 55)); // NOI18N
        jLabelWel.setText("Welcome ");

        BnameTextField.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        BnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnameTextFieldActionPerformed(evt);
            }
        });

        AnameTextField.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        AnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnameTextFieldActionPerformed(evt);
            }
        });

        PrcTextField.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        PrcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrcTextFieldActionPerformed(evt);
            }
        });
        PrcTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrcTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("Book Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("Author ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setText("Price");

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jButtonAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAddKeyPressed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("Book ID");

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        DeleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        DeleteButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DeleteButtonKeyPressed(evt);
            }
        });

        EditButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        EditButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EditButtonKeyPressed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Book ID", "Author", "Price"
            }
        ));
        jTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableMouseMoved(evt);
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel6.setText("Search");

        SearchTextField.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        SearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelWel, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(546, 546, 546))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelWel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrcTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrcTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrcTextFieldActionPerformed

    private void BnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnameTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BnameTextFieldActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
//                    Login_Page lg = new Login_Page();
//                    lg.setVisible(true);
//                    lg.pack();
//                    lg.setLocationRelativeTo(null);
//                    lg.setResizable(false);
//                    this.dispose();
       std.fillJTable(jTable, "");
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             jButtonAdd.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

     public boolean verifyText() {
         
         if(BnameTextField.getText().equals("") || AnameTextField.getText().equals("") || PrcTextField.getText().equals("") )
         {
             JOptionPane.showMessageDialog(null, "One or more fields are empty");
             return false;
         } 
        
         else {
          
             return true;   
         }
         
         
     }

   
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String Bname = BnameTextField.getText();
        String Aname= AnameTextField.getText();
        String Price = PrcTextField.getText();
        
        if (verifyText()) {  
            
        int id = Integer.valueOf(IDLabel.getText());
        std.InsertDeleteData('i', Bname, id, Aname, Price);
         DefaultTableModel model = (DefaultTableModel)jTable.getModel();
         std.fillJTable(jTable, "");
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             
        } 
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void PrcTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrcTextFieldKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PrcTextFieldKeyTyped

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2KeyPressed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)jTable.getModel();
         
         BnameTextField.setText(model.getValueAt(rowIndex, 0).toString());
         IDLabel.setText(model.getValueAt(rowIndex, 1).toString());
         AnameTextField.setText(model.getValueAt(rowIndex, 2).toString());
         PrcTextField.setText(model.getValueAt(rowIndex, 3).toString());
         jButtonAdd.setEnabled(false);
         
        
    }//GEN-LAST:event_jTableMouseClicked

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void SearchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextFieldKeyTyped
        // TODO add your handling code here:
        jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
        std.fillJTable(jTable, SearchTextField.getText());
        
    }//GEN-LAST:event_SearchTextFieldKeyTyped

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if(BnameTextField.getText().equals(""))
        {   
            JOptionPane.showMessageDialog(null, "No Data Selected!");
           
        } 
        else {
            int id = Integer.valueOf(IDLabel.getText());
             std.InsertDeleteData('d', null, id, null, null);
             std.fillJTable(jTable, "");
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             jButtonAdd.setEnabled(true);
        }
      

    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        String Bname = BnameTextField.getText();
        String Aname= AnameTextField.getText();
        String Price = PrcTextField.getText();
        int id = Integer.valueOf(IDLabel.getText());
        
        if(BnameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No Data Selected");
            
        } else {
            std.InsertDeleteData('u', Bname, id, Aname, Price);
            jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             jButtonAdd.setEnabled(true);
        }
         
                         
    }//GEN-LAST:event_EditButtonActionPerformed

    private void jTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyReleased
        // TODO add your handling code here:
        int rowIndex = jTable.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)jTable.getModel();
         
         BnameTextField.setText(model.getValueAt(rowIndex, 0).toString());
         IDLabel.setText(model.getValueAt(rowIndex, 1).toString());
         AnameTextField.setText(model.getValueAt(rowIndex, 2).toString());
         PrcTextField.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_jTableKeyReleased

    private void AnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnameTextFieldActionPerformed

    private void jTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTableKeyTyped

    private void jTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableKeyPressed

    private void jTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMouseMoved

    private void jButtonCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            Login_Page lg = new Login_Page();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setResizable(false);
            this.dispose();
            
            
        }
    }//GEN-LAST:event_jButtonCancelKeyPressed

    private void jButtonAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAddKeyPressed
        // TODO add your handling code here:
        String Bname = BnameTextField.getText();
        String Aname= AnameTextField.getText();
        String Price = PrcTextField.getText();
        
        if (verifyText()) {  
            
        int id = Integer.valueOf(IDLabel.getText());
        std.InsertDeleteData('i', Bname, id, Aname, Price);
         DefaultTableModel model = (DefaultTableModel)jTable.getModel();
         std.fillJTable(jTable, "");
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
        }
    }//GEN-LAST:event_jButtonAddKeyPressed

    private void DeleteButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DeleteButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             if(BnameTextField.getText().equals(""))
        {   
            JOptionPane.showMessageDialog(null, "No Data Selected!");
           
        } 
        else {
            int id = Integer.valueOf(IDLabel.getText());
             std.InsertDeleteData('d', null, id, null, null);
             std.fillJTable(jTable, "");
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             jButtonAdd.setEnabled(true);
             
             
        }
        }
    }//GEN-LAST:event_DeleteButtonKeyPressed

    private void EditButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER); {
        String Bname = BnameTextField.getText();
        String Aname= AnameTextField.getText();
        String Price = PrcTextField.getText();
        int id = Integer.valueOf(IDLabel.getText());
        
        if(BnameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No Data Selected");
            
        } else {
            std.InsertDeleteData('u', Bname, id, Aname, Price);
            jTable.setModel(new DefaultTableModel(null, new Object[] {"Name", "ID", "Author", "Price"})); 
             std.fillJTable(jTable, SearchTextField.getText());
             IDLabel.setText(Integer.toString(RecordEntry.countData("books")));
             BnameTextField.setText("");
             AnameTextField.setText("");
             PrcTextField.setText("");
             jButtonAdd.setEnabled(true);
        }
    }
        
    }//GEN-LAST:event_EditButtonKeyPressed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnameTextField;
    private javax.swing.JTextField BnameTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    public static javax.swing.JLabel IDLabel;
    private javax.swing.JTextField PrcTextField;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabelWel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
